/**
 * generate-sitemap.js
 * Reads content/posts.json and writes a fresh sitemap.xml.
 * Runs automatically on every Netlify deploy via package.json "build" script.
 */

const fs   = require('fs');
const path = require('path');

const BASE_URL = 'https://www.klevermedia.co.za';
const ROOT     = path.join(__dirname, '..');
const today    = new Date().toISOString().split('T')[0];

// Load posts
const postsFile = path.join(ROOT, 'content', 'posts.json');
const posts     = JSON.parse(fs.readFileSync(postsFile, 'utf8')).posts || [];

// Only include posts that have an actual HTML file
const publishedPosts = posts.filter(function (p) { return p.postFile; });

const postUrls = publishedPosts.map(function (p) {
  return [
    '  <url>',
    '    <loc>' + BASE_URL + '/work/' + p.postFile + '</loc>',
    '    <lastmod>' + (p.date || today) + '</lastmod>',
    '    <changefreq>yearly</changefreq>',
    '    <priority>0.7</priority>',
    '  </url>'
  ].join('\n');
}).join('\n');

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Auto-generated by scripts/generate-sitemap.js — do not edit manually -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  '',
  '  <!-- Core pages -->',
  '  <url>',
  '    <loc>' + BASE_URL + '/</loc>',
  '    <lastmod>' + today + '</lastmod>',
  '    <changefreq>monthly</changefreq>',
  '    <priority>1.0</priority>',
  '  </url>',
  '',
  '  <url>',
  '    <loc>' + BASE_URL + '/services.html</loc>',
  '    <lastmod>' + today + '</lastmod>',
  '    <changefreq>monthly</changefreq>',
  '    <priority>0.9</priority>',
  '  </url>',
  '',
  '  <url>',
  '    <loc>' + BASE_URL + '/work.html</loc>',
  '    <lastmod>' + today + '</lastmod>',
  '    <changefreq>weekly</changefreq>',
  '    <priority>0.8</priority>',
  '  </url>',
  '',
  '  <url>',
  '    <loc>' + BASE_URL + '/ghostwriting.html</loc>',
  '    <lastmod>' + today + '</lastmod>',
  '    <changefreq>monthly</changefreq>',
  '    <priority>0.7</priority>',
  '  </url>',
  '',
  '  <!-- Work posts (auto-generated from content/posts.json) -->',
  postUrls,
  '',
  '</urlset>'
].join('\n');

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);
console.log('✓ sitemap.xml regenerated — ' + publishedPosts.length + ' work post(s) included.');
