/**
 * generate-sitemap.js
 * Reads content/posts.json and writes a fresh sitemap.xml.
 * Runs automatically on every Netlify deploy via package.json "build" script.
 */

const fs   = require('fs');
const path = require('path');

const BASE_URL = 'https://www.klevermedia.co.za';
const ROOT     = path.join(__dirname, '..');
const today    = new Date().toISOString().split('T')[0];

// Core pages, including every service pillar page.
// Add a new pillar page here when one is built, or it will never reach the sitemap.
const CORE_PAGES = [
  { loc: '/', changefreq: 'monthly', priority: '1.0' },
  { loc: '/services.html', changefreq: 'monthly', priority: '0.9' },
  { loc: '/work.html', changefreq: 'weekly', priority: '0.8' },
  { loc: '/insights.html', changefreq: 'weekly', priority: '0.8' },
  { loc: '/ghostwriting.html', changefreq: 'monthly', priority: '0.7' },
  { loc: '/personal-branding.html', changefreq: 'monthly', priority: '0.7' },
  { loc: '/website-management.html', changefreq: 'monthly', priority: '0.7' },
  { loc: '/search-marketing.html', changefreq: 'monthly', priority: '0.7' },
  { loc: '/impact-communications.html', changefreq: 'monthly', priority: '0.7' },
  { loc: '/marketing-strategy.html', changefreq: 'monthly', priority: '0.7' },
  { loc: '/social-media-management.html', changefreq: 'monthly', priority: '0.7' }
];

const corePageUrls = CORE_PAGES.map(function (p) {
  return [
    '  <url>',
    '    <loc>' + BASE_URL + p.loc + '</loc>',
    '    <lastmod>' + today + '</lastmod>',
    '    <changefreq>' + p.changefreq + '</changefreq>',
    '    <priority>' + p.priority + '</priority>',
    '  </url>'
  ].join('\n');
}).join('\n\n');

// Load posts
const postsFile = path.join(ROOT, 'content', 'posts.json');
const posts     = JSON.parse(fs.readFileSync(postsFile, 'utf8')).posts || [];

// Only include posts that have an actual HTML file
const publishedPosts = posts.filter(function (p) { return p.postFile; });

const postUrls = publishedPosts.map(function (p) {
  return [
    '  <url>',
    '    <loc>' + BASE_URL + '/work/' + p.postFile + '</loc>',
    '    <lastmod>' + (p.date || today) + '</lastmod>',
    '    <changefreq>yearly</changefreq>',
    '    <priority>0.7</priority>',
    '  </url>'
  ].join('\n');
}).join('\n');

// Load insights posts (same shape/pattern as content/posts.json)
const insightsFile = path.join(ROOT, 'content', 'insights.json');
const insightsPosts = fs.existsSync(insightsFile)
  ? (JSON.parse(fs.readFileSync(insightsFile, 'utf8')).posts || [])
  : [];
const publishedInsights = insightsPosts.filter(function (p) { return p.postFile; });

const insightUrls = publishedInsights.map(function (p) {
  return [
    '  <url>',
    '    <loc>' + BASE_URL + '/insights/' + p.postFile + '</loc>',
    '    <lastmod>' + (p.date || today) + '</lastmod>',
    '    <changefreq>yearly</changefreq>',
    '    <priority>0.6</priority>',
    '  </url>'
  ].join('\n');
}).join('\n');

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Auto-generated by scripts/generate-sitemap.js — do not edit manually -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  '',
  '  <!-- Core pages -->',
  corePageUrls,
  '',
  '  <!-- Work posts (auto-generated from content/posts.json) -->',
  postUrls,
  '',
  '  <!-- Insights posts (auto-generated from content/insights.json) -->',
  insightUrls,
  '',
  '</urlset>'
].join('\n');

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);
console.log('✓ sitemap.xml regenerated — ' + CORE_PAGES.length + ' core page(s), ' + publishedPosts.length + ' work post(s), ' + publishedInsights.length + ' insight post(s) included.');
